# Copyright:
# ----------------------------------------------------------------------------
# This confidential and proprietary software may be used only as authorized
# by a licensing agreement from ARM Limited.
#      (C) COPYRIGHT 2012 ARM Limited, ALL RIGHTS RESERVED
# The entire notice above must be reproduced on all authorized copies and
# copies may only be made to the extent permitted by a licensing agreement
# from ARM Limited.
# ----------------------------------------------------------------------------
#

obj-y += mali_kbase_config_manta.o
obj-y += mali_kbase_platform.o
obj-y += mali_kbase_dvfs.o
obj-y += mali_kbase_gpu_busy.o
